custom_form/urls.py
from django.urls import include, path
from django.contrib.auth import views as auth_views

from .views import (
        AddFieldView, CustomFormView,
        delete_field,
)

app_name = 'new_custom_form'

urlpatterns = [
    path('', AddFieldView.as_view(), name='add_field'),
    path('deletefield/<str:field>', delete_field, name='delete_field'),
    path('customform', CustomFormView.as_view(), name='form'),
]

new_custom_form/urls.py
from django.urls import path

from .views import (
        AddFieldView, CustomFormView,
        delete_field,
)

app_name = 'new_custom_form'

urlpatterns = [
    path('', AddFieldView.as_view(), name='add_field'),
    path('deletefield/<int:id>', delete_field, name='delete_field'),
    path('form/<str:form_name>', CustomFormView.as_view(), name='form'),
]

shiyanlou_form/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', include('new_custom_form.urls')),
    path('', include('new_custom_form.urls')),
]

new_custom_form/models.py
from django.db import models


class FormModel(models.Model):
    form_name = models.CharField(max_length=100, unique=True, null=False, blank=False)
    flag = models.BooleanField(default=False)

    class Meta:
        verbose_name = '表单'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.form_name


class FieldModel(models.Model):
    form = models.ForeignKey(FormModel, on_delete=models.CASCADE)

    field = models.CharField(max_length=100, null=False, blank=False)
    field_name = models.CharField(max_length=100, null=False, blank=False)
    field_type = models.CharField(max_length=100, null=False, blank=False)
    # field_options = models.CharField(null=True, blank=True)     # 选择性字段的可选项

    class Meta:
        verbose_name = '字段'
        verbose_name_plural = verbose_name

    def __str__(self):
        str = self.field + '({})'.format(self.form)
        return str

new_custom_form/forms.py
from django import forms

from .models import FormModel, FieldModel


class FormForm(forms.ModelForm):
    form_name = forms.HiddenInput()

    class Meta:
        model = FormModel
        fields = []


class CreateFieldForm(forms.ModelForm):
    form_name = forms.CharField(max_length=100, required=True)
    field = forms.CharField(max_length=100, required=True)
    field_name = forms.CharField(max_length=100, required=True)
    field_type = forms.CharField(max_length=100, required=True)

    class Meta:
        model = FieldModel
        fields = ['form_name', 'field', 'field_name', 'field_type']

new_custom_form/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import FormView, CreateView
from django.db import connection
from django import forms
from django.contrib import messages

from .models import FormModel, FieldModel
from .forms import FormForm, CreateFieldForm


class AddFieldView(CreateView):
    """
    添加表单字段
    POST 方式传入字典数据
    将字段数据存入数据库
    """
    model = FieldModel
    form_class = CreateFieldForm
    template_name = 'new_custom_form/create_form.html'

    def get_context_data(self, **kwargs):
        """
        向模板传入创建的字段和表单
        """
        objs = FieldModel.objects.all()
        kwargs['fields'] = objs
        forms = FormModel.objects.all()
        kwargs['forms'] = forms

        return super(AddFieldView, self).get_context_data(**kwargs)

    def form_valid(self, form):
        field = form.save(commit=False)
        form_name = form.cleaned_data['form_name']
        form = FormModel.objects.filter(form_name=form_name).first()

        # 如果表单不存在,则创建该表单
        if not form:
            form = FormModel.objects.create(form_name=form_name)

        # 当flag=True,代表此表已经添加过数据,禁止编辑
        if form.flag==1:
            messages.error(self.request, '该表单已创建实例,无法编辑')
            return redirect('new_custom_form:add_field')
        else:
            field.form = form
            field.save()
            return redirect('new_custom_form:add_field')


def delete_field(request, id):
    """
    删除字段
    """
    field = FieldModel.objects.filter(id=id).first()

    # 判断表单是否已经创建实例
    if field.form.flag==1:
        messages.error(request, '该表单已创建实例,无法编辑')
    else:
        FieldModel.objects.filter(id=id).delete()

    return redirect('new_custom_form:add_field')


class CustomFormView(FormView):
    template_name = 'new_custom_form/form.html'

    def set_form(self, form_name):
        """
        创建form
        """
        # 指定表单
        custom_form = self.get_form(form_class=FormForm)
        form = FormModel.objects.filter(form_name=form_name).first()
        # 指定字段, 这一步考虑了字段的顺序
        fields = FieldModel.objects.filter(form=form).order_by('id')
        for field in fields:
            # 根据field_type来设立不同类型的字段
            if field.field_type == 'int':
                custom_form.fields[field.field] = forms.IntegerField(label=field.field_name)
            # 在这里可以添加代码,以考虑更多的字段类型
            else:
                custom_form.fields[field.field] = forms.CharField(label=field.field_name)

        return custom_form

    def get(self, request, *args, **kwargs):
        custom_form = self.set_form(kwargs['form_name'])
        data = {'form_name': kwargs['form_name'],
                'custom_form': custom_form}

        return render(request, 'new_custom_form/form.html', data)

    def post(self, request, *args, **kwargs):
        self.object = None
        form = self.set_form(kwargs['form_name'])
        print(form)
        if form.is_valid():
            print('验证成功')
            return self.form_valid(form, kwargs['form_name'])
        else:
            print('验证失败')
            return self.form_invalid(form)

    def form_valid(self, form, form_name):
        form.save(commit=False)
        cursor = connection.cursor()
        custom_form = FormModel.objects.filter(form_name=form_name).first()

        # 如果表不存在,先创建表
        if custom_form.flag==0:
            # 按添加顺序读取字段
            fields = FieldModel.objects.filter(form=custom_form).order_by('id')
            # 创建 sql 语句
            fields_list = []
            for field in fields:
                str = '{0} varchar(50) not null'.format(field.field)
                fields_list.append(str)
            field_str = ','.join(fields_list)
            create_sql = 'create table {0}(' \
                         'id int(3) auto_increment not null primary key,' \
                         '{1}' \
                         ');'.format(form_name, field_str)
            # print(create_sql)
            cursor.execute(create_sql)
            # 将模型改为不可编辑
            FormModel.objects.filter(form_name=form_name).update(flag=1)

        # 向表中传入数据
        key_list = []
        value_list = []
        for key, value in form.cleaned_data.items():
            if key != 'form_name':
                key_list.append(key)
                value_list.append(value)

        key_str = ','.join(key_list)
        value_str = '\''+'\',\''.join(value_list)+'\''
        insert_sql = 'INSERT INTO {0} ({1}) VALUES ({2});'.format(form_name, key_str, value_str)
        cursor.execute(insert_sql)

        return redirect('/form/{}'.format(form_name))

    def form_invalid(self, form):
        messages.error(self.request, '输入表单无效')
        return redirect('new_custom_form:add_field')

new_custom_form/templates/new_custom_form/create_form.html
{% extends 'new_custom_form/master.html' %}
{% load staticfiles %}


{% block main %}
    <div class="box">
        <div class="header"><a href="/">Listen2nite</a><span class="chevron"> > </span> 创建自定义表单 </div>
        
        <div class="inner">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
            <form method="post" action="{% url 'new_custom_form:add_field' %}" novalidate>
                {% csrf_token %}
                <table cellpadding="5" cellspacing="0" border="0" width="100%">
                    <tbody>
                        <tr>
                            <td width="120" align="right">所属表单</td>
                            <td width="auto" align="left">
                                {{ form.form_name }}
                            </td>
                        </tr>
                        <tr>
                            <td width="120" align="right">字段</td>
                            <td width="auto" align="left">
                                {{ form.field }}
                            </td>
                        </tr>
                        <tr>
                            <td width="120" align="right">字段名称</td>
                            <td width="auto" align="left">
                                {{ form.field_name }}
                            </td>
                        </tr>
                        <tr>
                            <td width="120" align="right">字段类型</td>
                            <td width="auto" align="left">
                                {{ form.field_type }}
                            </td>
                        </tr>
                        <tr>
                            <td width="120" align="right"></td>
                            <td width="auto" align="left">
                                <input type="submit" class="btn btn-sm btn-secondary" value="添加">
                            </td>
                        </tr>
                    </tbody>
                </table>
            </form>
        </div>
    </div>

     <div class="box">
        <div class="inner">
            <div class="header">已有字段</div>
                <table cellpadding="5" cellspacing="0" border="0" width="100%">
                    <tbody>
                        <tr>
                            <td width="120">所属表单</td>
                            <td width="120">字段</td>
                            <td width="120">字段名</td>
                            <td width="120">字段类型</td>
                        </tr>
                        {% for field in fields %}
                        <tr>
                            <td width="120">
                                {{ field.form }}
                            </td>
                            <td width="120">
                                {{ field.field }}
                            </td>
                            <td width="120">
                                {{ field.field_name }}
                            </td>
                            <td width="120">
                                {{ field.field_type }}
                            </td>
                            <td width="120">
                                <a href="{% url 'new_custom_form:delete_field' field.id %}">删除</a>
                            </td>
                        </tr>
                        {% endfor %}

                    </tbody>
                </table>
        </div>
    </div>


{% endblock %}

{% block rightbar %}
        <div class="box">
            <div class="cell">
                <strong>已存在表单</strong>
            </div>
            <div class="inner">
                {% for form in forms %}
                    <div><a href="{% url 'new_custom_form:form' form %}">{{ form }}</a></div>
                {% endfor %}
            </div>
        </div>

{% endblock %}

new_custom_form/templates/new_custom_form/form.html
{% extends 'new_custom_form/master.html' %}
{% load staticfiles %}


{% block main %}
    <div class="box">
        <div class="header"><a href="/">Listen2nite</a><span class="chevron"> > </span> 自定义表单 {{ form_name }}</div>
        <div class="header"><a href="{% url 'new_custom_form:add_field' %}">进入创建表单页面</a></div>
        <div class="inner">
            <form method="post" action="" novalidate>
                {% csrf_token %}
                <table cellpadding="5" cellspacing="0" border="0" width="100%">
                    <tbody>
                        {% for field in custom_form %}
                            <tr>
                                <td width="120" align="right">{{ field.label }}</td>
                                <td width="auto" align="left">{{ field }}</td>
                        </tr>
                        {% endfor %}
                        <tr>
                            <td width="120" align="right"></td>
                            <td width="auto" align="left">
                                <input type="submit" class="btn btn-sm btn-secondary" value="提交">
                            </td>
                        </tr>
                    </tbody>
                </table>
            </form>
        </div>
    </div>
{% endblock %}


{% block JS %}

{% endblock %}

new_custom_form/templates/new_custom_form/master.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load static %}